### ISSUE TITLE
Plan Your Project

### ISSUE THREAD

**Issue by arniejolo** [arniejolo/web-design-2-independent-project#1]
[jolo-arnie-030-plan-your-project.pdf](https://github.com/arniejolo/web-design-2-independent-project-1/files/7541071/jolo-arnie-030-plan-your-project.pdf)

@thatkidmadrid

**Comment by arniejolo** [comment]
@anna-pokhilenko

Hi Anna, 

I'm not totally sure where to link/tag my background image but right now my background image is not the right size etc.

**Comment by thatkidmadrid** [comment]
Could you please provide some more detail for where you want the background image to appear?
