### ISSUE TITLE
Skip Link Error

### ISSUE THREAD

**Issue by arniejolo** [arniejolo/web-design-2-independent-project#2]
@thatkidmadrid

Hi,

I'm getting an error about skip links with the suggestion to input tabindex="0" to the element with the matching id. I'm not sure what element it is pointing out. I have links at the bottom of my main page but it is not meant to be skip links but secondary links to my other pages.

**Comment by thatkidmadrid** [comment]
can you please send the full screenshot for context?
Also, please make sure you push all your changes so I can try on my end

**Comment by arniejolo** [comment]
<img width="1792" alt="Screen Shot 2021-12-04 at 9 21 15 PM" src="https://user-images.githubusercontent.com/77504965/144730986-51416be4-d574-46bd-8db6-9b9ac9d92bef.png">

**Comment by thatkidmadrid** [comment]
ok, so the error means that there is something in your skip links that either doesn't exist or isn't focusable. You can add tabindex="0" if it is something that isn't focusable by default.

for the error about your background image, you will want to write `../` to escape the current folder level.

where you have `url(..."/images/gradient-1.jpg")`, you want to write it like `url("../images/gradient-1.jpg")`

**Comment by thatkidmadrid** [comment]
I think what the skip link error is complaining about is you have an id `section1` but the actual section has the id `section1main`

**Comment by thatkidmadrid** [comment]
[favicon.ico.zip](https://github.com/arniejolo/web-design-2-independent-project-1/files/7655097/favicon.ico.zip)
Also here is a new favicon that includes the missing size

I'm curious what you used to create that favicon that's missing the 48x48 size

**Comment by arniejolo** [comment]
Thank you - I changed the link name and it worked.

& I used X-Icon Editor that was on the Images for the Web page to create the favicon
